apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-hello-world
  name: spark-hello-world
  #namespace: devops-garage
spec:
  type: LoadBalancer 
  ports:
  - name: spark-hello-world
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spark-hello-world
  sessionAffinity: None
