apiVersion: v1
kind: Service
metadata:
  labels:
    app: weatheradmin
  name: weatheradmin
  #namespace: devops-garage
spec:
  type: NodePort 
  ports:
  - name: weatheradmin
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weatheradmin
  sessionAffinity: None
